trigger:
- main

pool: 
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  project: '**/MongoAuthWebApi.csproj'
  tag: '$(Build.BuildId)'
  DOCKER_BUILDKIT: 1

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK 8.x'
  inputs:
    packageType: 'sdk'
    version: '8.x'

- task: DotNetCoreCLI@2
  displayName: 'Restore Packages'
  inputs:
    command: 'restore'
    projects: '$(project)'

- task: DotNetCoreCLI@2
  displayName: 'Build Project'
  inputs:
    command: 'build'
    projects: '$(project)'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Run Tests'
  inputs:
    command: 'test'
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
    nobuild: true

- task: DotNetCoreCLI@2
  displayName: 'Publish Project'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(project)'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false

- task: Docker@2
  displayName: 'Build and Push Docker Image'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
  inputs:
    containerRegistry: 'DOCR'
    repository: 'gsherwin360/mongoauthwebapi'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(tag)
      latest